- definitions.json
- package.json
> fix: request replace type def

- definitions.json
- package.json
> fix: rm issue type def (now issue-request)

- definitions.json
- package.json
> refactor: consolidate json rpc request & response types

- definitions.json
- package.json
> fix: add withdraw request vault json rpc type def

- definitions.json
- package.json
> refactor: setBtcAddress -> updateBtcAddress

- definitions.json
- package.json
> refactor: staked-relayer / vault account id response

- definitions.json
- package.json
> feat: add typedef for 'getCollateralizationFromVaultAndCollateral'

- definitions.json
- package.json
> feat: add vault wallet typedef

- definitions.json
- package.json
> fix(replace): rpc types

- definitions.json
- package.json
> refactor: explicit btc address payload type

- definitions.json
- package.json
> chore: add storage version type

- definitions.json
- package.json
> fix: witness version uses separate enum

- definitions.json
- package.json
> fix: decorate remaining rpc calls

- definitions.json
- package.json
> feat: staked relayer votes, proposal status, btc public key 

- definitions.json
- package.json
> refactor: add vault public key to issue request

- definitions.json
- package.json
> fix: add backing collateral to vault and account id to rich block header

- definitions.json
- package.json
> fix: add to-be-replaced to vault

- definitions.json
- package.json
> refactor: vault, nomination, sla types & remove jsonrpc requests

- definitions.json
- package.json
> refactor: integrated staking pallet, btc-relay audit fixes

- definitions.json
- package.json
> chore: specify types for parachain v0.10.0

- definitions.json
- package.json
> feat: decorate verifyBlockHeaderInclusion RPC

- definitions.json
- package.json
> refactor!: rename interbtc to ibtc

- definitions.json
- package.json
> feat: add foreign asset id

- definitions.json
- package.json
> WIP Add rpc definitions for AMM pallets
